export const MACHINE: Record<number, string> = {
  0x0: 'UNKNOWN',
  0x14c: 'i386 (x86)',
  0x162: 'MIPS R3000',
  0x166: 'MIPS R4000',
  0x169: 'MIPS WCE v2',
  0x184: 'Alpha AXP',
  0x1a2: 'SH3',
  0x1a3: 'SH3 DSP',
  0x1a6: 'SH4',
  0x1a8: 'SH5',
  0x1c0: 'ARM',
  0x1c2: 'ARM Thumb',
  0x1c4: 'ARMv7 Thumb-2',
  0x1d3: 'AM33',
  0x1f0: 'PowerPC',
  0x1f1: 'PowerPC FP',
  0x200: 'Itanium (IA64)',
  0x266: 'MIPS16',
  0x284: 'Alpha 64',
  0x366: 'MIPS FPU',
  0x466: 'MIPS16 FPU',
  0x520: 'Tricore',
  0xcef: 'CEF',
  0xebc: 'EFI Byte Code',
  0x8664: 'x64 (AMD64)',
  0x9041: 'M32R',
  0xaa64: 'ARM64',
  0xc0ee: 'CEE',
};

export const SUBSYSTEM: Record<number, string> = {
  0: 'Unknown',
  1: 'Native (device driver / native process)',
  2: 'Windows GUI',
  3: 'Windows Console',
  5: 'OS/2 Console',
  7: 'POSIX Console',
  8: 'Native Windows 9x driver',
  9: 'Windows CE GUI',
  10: 'EFI Application',
  11: 'EFI Boot Service Driver',
  12: 'EFI Runtime Driver',
  13: 'EFI ROM',
  14: 'Xbox',
  16: 'Windows Boot Application',
};

export interface FlagDef {
  bit: number;
  name: string;
  desc: string;
}

export const FILE_CHARACTERISTICS: FlagDef[] = [
  { bit: 0x0001, name: 'RELOCS_STRIPPED', desc: 'Base relocations were stripped — the image can only load at its preferred base.' },
  { bit: 0x0002, name: 'EXECUTABLE_IMAGE', desc: 'The image is valid and can be run. Cleared for object files / broken links.' },
  { bit: 0x0004, name: 'LINE_NUMS_STRIPPED', desc: 'COFF line numbers removed (deprecated).' },
  { bit: 0x0008, name: 'LOCAL_SYMS_STRIPPED', desc: 'COFF local symbol table removed (deprecated).' },
  { bit: 0x0010, name: 'AGGRESSIVE_WS_TRIM', desc: 'Aggressively trim the working set (obsolete).' },
  { bit: 0x0020, name: 'LARGE_ADDRESS_AWARE', desc: 'Can handle addresses beyond 2 GB. Essential for 32-bit processes on /3GB or WOW64.' },
  { bit: 0x0080, name: 'BYTES_REVERSED_LO', desc: 'Little endian marker (obsolete).' },
  { bit: 0x0100, name: '32BIT_MACHINE', desc: 'Machine is based on a 32-bit word architecture.' },
  { bit: 0x0200, name: 'DEBUG_STRIPPED', desc: 'Debug info removed from the image and lives in a separate .DBG/.PDB file.' },
  { bit: 0x0400, name: 'REMOVABLE_RUN_FROM_SWAP', desc: 'If on removable media, copy to and run from the swap file.' },
  { bit: 0x0800, name: 'NET_RUN_FROM_SWAP', desc: 'If on network media, copy to and run from the swap file.' },
  { bit: 0x1000, name: 'SYSTEM', desc: 'The image is a system file, not a user program.' },
  { bit: 0x2000, name: 'DLL', desc: 'The image is a dynamic-link library. Loaded into a host process, entry point is DllMain.' },
  { bit: 0x4000, name: 'UP_SYSTEM_ONLY', desc: 'Should only be run on a uniprocessor machine.' },
  { bit: 0x8000, name: 'BYTES_REVERSED_HI', desc: 'Big endian marker (obsolete).' },
];

export const DLL_CHARACTERISTICS: FlagDef[] = [
  { bit: 0x0020, name: 'HIGH_ENTROPY_VA', desc: 'Supports 64-bit ASLR entropy — the loader may relocate anywhere in the full 64-bit space.' },
  { bit: 0x0040, name: 'DYNAMIC_BASE', desc: 'ASLR: the image can be relocated at load time. Requires a valid .reloc section.' },
  { bit: 0x0080, name: 'FORCE_INTEGRITY', desc: 'Code integrity checks are enforced — the image must be signed.' },
  { bit: 0x0100, name: 'NX_COMPAT', desc: 'DEP compatible — non-executable pages are enforced for data.' },
  { bit: 0x0200, name: 'NO_ISOLATION', desc: 'Image is isolation aware but should not be isolated (side-by-side manifest ignored).' },
  { bit: 0x0400, name: 'NO_SEH', desc: 'Does not use structured exception handling — no SE handler may be called.' },
  { bit: 0x0800, name: 'NO_BIND', desc: 'Do not bind the image (import addresses must not be pre-computed).' },
  { bit: 0x1000, name: 'APPCONTAINER', desc: 'Image must execute inside an AppContainer (UWP / sandboxed).' },
  { bit: 0x2000, name: 'WDM_DRIVER', desc: 'The image is a WDM device driver.' },
  { bit: 0x4000, name: 'GUARD_CF', desc: 'Control Flow Guard: indirect calls are validated against a bitmap of valid targets.' },
  { bit: 0x8000, name: 'TERMINAL_SERVER_AWARE', desc: 'Safe to run under Terminal Services / Remote Desktop sessions.' },
];

export const SECTION_FLAGS: FlagDef[] = [
  { bit: 0x00000008, name: 'TYPE_NO_PAD', desc: 'Section should not be padded to the next boundary (object files only).' },
  { bit: 0x00000020, name: 'CNT_CODE', desc: 'Contains executable machine code.' },
  { bit: 0x00000040, name: 'CNT_INITIALIZED_DATA', desc: 'Contains initialized data that is stored in the file.' },
  { bit: 0x00000080, name: 'CNT_UNINITIALIZED_DATA', desc: 'Contains uninitialized data (BSS) — zero-filled by the loader, occupies no file space.' },
  { bit: 0x00000200, name: 'LNK_INFO', desc: 'Contains comments or other linker info (e.g. .drectve).' },
  { bit: 0x00000800, name: 'LNK_REMOVE', desc: 'Section will not become part of the image.' },
  { bit: 0x00001000, name: 'LNK_COMDAT', desc: 'Section contains COMDAT data (folded duplicates).' },
  { bit: 0x00008000, name: 'GPREL', desc: 'Data referenced through the global pointer.' },
  { bit: 0x01000000, name: 'LNK_NRELOC_OVFL', desc: 'Section contains extended relocations (>65535).' },
  { bit: 0x02000000, name: 'MEM_DISCARDABLE', desc: 'Can be discarded once used — typical for .reloc, which the loader drops after fixups.' },
  { bit: 0x04000000, name: 'MEM_NOT_CACHED', desc: 'Cannot be cached.' },
  { bit: 0x08000000, name: 'MEM_NOT_PAGED', desc: 'Not pageable — stays resident (drivers).' },
  { bit: 0x10000000, name: 'MEM_SHARED', desc: 'Shared across all processes that map the image — a classic source of shared-state bugs.' },
  { bit: 0x20000000, name: 'MEM_EXECUTE', desc: 'Pages are executable.' },
  { bit: 0x40000000, name: 'MEM_READ', desc: 'Pages are readable.' },
  { bit: 0x80000000, name: 'MEM_WRITE', desc: 'Pages are writable. W+X together is a red flag for exploit mitigation.' },
];

export const DATA_DIRECTORY_NAMES = [
  'Export Table',
  'Import Table',
  'Resource Table',
  'Exception Table',
  'Certificate Table',
  'Base Relocation Table',
  'Debug Directory',
  'Architecture',
  'Global Ptr',
  'TLS Table',
  'Load Config Table',
  'Bound Import',
  'Import Address Table',
  'Delay Import Descriptor',
  'CLR Runtime Header',
  'Reserved',
];

export const DEBUG_TYPE: Record<number, string> = {
  0: 'UNKNOWN',
  1: 'COFF',
  2: 'CODEVIEW (PDB link)',
  3: 'FPO',
  4: 'MISC',
  5: 'EXCEPTION',
  6: 'FIXUP',
  7: 'OMAP_TO_SRC',
  8: 'OMAP_FROM_SRC',
  9: 'BORLAND',
  10: 'RESERVED10',
  11: 'CLSID',
  12: 'VC_FEATURE',
  13: 'POGO (profile-guided optimization)',
  14: 'ILTCG',
  15: 'MPX',
  16: 'REPRO (reproducible build hash)',
  17: 'SPGO',
  20: 'EX_DLLCHARACTERISTICS',
};

export const RESOURCE_TYPE: Record<number, string> = {
  1: 'CURSOR',
  2: 'BITMAP',
  3: 'ICON',
  4: 'MENU',
  5: 'DIALOG',
  6: 'STRING',
  7: 'FONTDIR',
  8: 'FONT',
  9: 'ACCELERATOR',
  10: 'RCDATA',
  11: 'MESSAGETABLE',
  12: 'GROUP_CURSOR',
  14: 'GROUP_ICON',
  16: 'VERSION',
  17: 'DLGINCLUDE',
  19: 'PLUGPLAY',
  20: 'VXD',
  21: 'ANICURSOR',
  22: 'ANIICON',
  23: 'HTML',
  24: 'MANIFEST',
};

export const RELOC_TYPE: Record<number, string> = {
  0: 'ABSOLUTE (padding)',
  1: 'HIGH',
  2: 'LOW',
  3: 'HIGHLOW (32-bit)',
  4: 'HIGHADJ',
  5: 'MIPS_JMPADDR / ARM_MOV32 / RISCV_HIGH20',
  7: 'THUMB_MOV32 / RISCV_LOW12I',
  8: 'RISCV_LOW12S',
  9: 'MIPS_JMPADDR16',
  10: 'DIR64 (64-bit)',
};

/** Known Rich header product IDs (MSVC build provenance). Abbreviated but covers common tools. */
export const RICH_PRODUCT: Record<number, string> = {
  0x00: 'Unknown',
  0x01: 'Import (linker-generated)',
  0x02: 'Linker (v5.10)',
  0x03: 'Cvtomf',
  0x04: 'Linker',
  0x05: 'Cvtres',
  0x06: 'Utc11_Basic',
  0x07: 'Utc11_C',
  0x08: 'Utc12_Basic',
  0x09: 'Utc12_C',
  0x0a: 'Utc12_CPP',
  0x0b: 'AliasObj60',
  0x0c: 'VisualBasic60',
  0x0d: 'Masm613',
  0x0e: 'Masm710',
  0x0f: 'Linker511',
  0x10: 'Cvtomf511',
  0x11: 'Masm614',
  0x12: 'Linker512',
  0x13: 'Cvtomf512',
  0x14: 'Utc12_C_Std',
  0x15: 'Utc12_CPP_Std',
  0x16: 'Utc12_C_Book',
  0x17: 'Utc12_CPP_Book',
  0x18: 'Implib700',
  0x19: 'Cvtomf700',
  0x1a: 'Utc13_Basic',
  0x1b: 'Utc13_C',
  0x1c: 'Utc13_CPP',
  0x1d: 'Linker610',
  0x1e: 'Cvtomf610',
  0x1f: 'Linker601',
  0x20: 'Cvtomf601',
  0x21: 'Utc13_C_Std',
  0x22: 'Utc13_CPP_Std',
  0x23: 'Cvtpgd1300',
  0x24: 'Linker620',
  0x25: 'Cvtomf620',
  0x26: 'AliasObj70',
  0x27: 'Linker621',
  0x5a: 'Linker (VS2005+)',
  0x5e: 'Export',
  0x5f: 'Implib',
  0x60: 'Cvtres',
  0x61: 'Utc1500_C',
  0x62: 'Utc1500_CPP',
  0x6d: 'Utc1600_C (VS2010)',
  0x6e: 'Utc1600_CPP (VS2010)',
  0x83: 'Utc1700_C (VS2012)',
  0x84: 'Utc1700_CPP (VS2012)',
  0x91: 'Utc1800_C (VS2013)',
  0x92: 'Utc1800_CPP (VS2013)',
  0x9d: 'Utc1900_C (VS2015)',
  0x9e: 'Utc1900_CPP (VS2015)',
  0xff: 'Utc_Latest',
};
